### ISSUE TITLE
Does sylpheed still support NetNews?

### ISSUE THREAD

**Issue by dfiguera** [sylpheed-mail/sylpheed#1]
https://sylpheed.sraoss.jp/en/features.html says yes, but if I try to create a new account, the only options are POP3, IMAP4 and the Google variants.

**Comment by y-hiroyu** [comment]
You can still create News accounts by 'Configuration - Edit accounts... - Add'.

**Comment by dfiguera** [comment]
You're right. I was checking via Configuration -> Create new account
