### ISSUE TITLE
Gmail imap login failing

### ISSUE THREAD

**Issue by ghost** [sylpheed-mail/sylpheed#26]
Hi. I've added my gmail account to Sylpheed 3.7.0 on Fedora and the authentication is failing. I guess it should open a popup window with gmail login site as other email clients do. Here is the log when I try to "Rebuild folder tree":

```
* creating IMAP4 connection to imap.gmail.com:993 ...
* SSL certificate of imap.gmail.com previously accepted
[20:32:47] IMAP4< * OK Gimap ready for requests from 2800:2164:2000:296::3413 q38mb33063791oiw
[20:32:47] IMAP4> 1 CAPABILITY
[20:32:47] IMAP4< * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER
[20:32:47] IMAP4< 1 OK Thats all she wrote! q38mb33063791oiw
[20:32:47] IMAP4> 2 AUTHENTICATE PLAIN
[20:32:47] IMAP4< + 
[20:32:47] IMAP4> ****************
[20:32:47] IMAP4< 2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
** LibSylph-WARNING: [20:32:47] IMAP4 authentication failed.

** IMAP4 authentication failed.
[20:32:47] IMAP4> 3 LOGOUT
[20:32:48] IMAP4< * BYE Logout Requested q38mb33063791oiw
[20:32:48] IMAP4< 3 OK Quoth the raven, nevermore... q38mb33063791oiw
** LibSylph-WARNING: [20:32:48] Could not establish IMAP connection.

** Could not establish IMAP connection.
```

Triple check login credentials and they are ok.
Thx!

**Comment by robertszewczyk** [comment]
OAUTH support is not there in Sylpheed AFAIK.

**Comment by kimariterikishi** [comment]
Oauth2 is not supported by Sylpheed.
The solution, for example, in the case of GMail - especially if you also use 2FA - is to use the application password (16 characters, without spaces),
https://support.google.com/accounts/answer/185833
also, that you also enter your username and password (or application password) in the receiving and sending settings, and that you use one of the following three settings instead of Oauth2. The same in both places:
Automatic
LOGIN
PLAIN

Note: unfortunately, the use of the master password is only available in a 6-year fork. Currently, the password is stored in a plain text wall in the Sylpheed settings directory, which resides in your home directory.

**Comment by ghost** [comment]
> Oauth2 is not supported by Sylpheed. The solution, for example, in the case of GMail - especially if you also use 2FA - is to use the application password (16 characters, without spaces), https://support.google.com/accounts/answer/185833 also, that you also enter your username and password (or application password) in the receiving and sending settings, and that you use one of the following three settings instead of Oauth2. The same in both places: Automatic LOGIN PLAIN
> 
> Note: unfortunately, the use of the master password is only available in a 6-year fork. Currently, the password is stored in a plain text wall in the Sylpheed settings directory, which resides in your home directory.

Oh okay. To do this gmail asks me to turn on 2FA but I don't want to do that so that's ok. Thx for the quick response.

**Comment by kimariterikishi** [comment]
> Oh okay. To do this gmail asks me to turn on 2FA but I don't want to do that so that's ok. Thx for the quick response.

Great, welcome. :)

Note: When using 2FA, a system reboot is required, then the email account is affected:
_File > Mailbox > Rebuild Folder Tree._

**Comment by luxzg** [comment]
> Oauth2 is not supported by Sylpheed. The solution, for example, in the case of GMail - especially if you also use 2FA - is to use the application password (16 characters, without spaces), https://support.google.com/accounts/answer/185833 

In short this is the answer, thanks!

Step by step walkthrough:

- open https://support.google.com/mail/answer/185833
- read the how-to about making app passwords
- click link to "Create and manage your app passwords" that leads to https://myaccount.google.com/apppasswords
- create new app password, for app name just enter whatever like "Sylpheed login"
- it will generate a 16-char password, copy it
- go to your Sylpheed -> Configuration -> Edit accounts
- click Gmail one, select Edit
- on first Basic tab paste the 16-char app password in the Password field
- save the changes (Apply, OK, Close)
- refresh inbox (right click, check for new messages)
